### ISSUE TITLE
Problem with Docker

### ISSUE THREAD

**Issue by mariuszkopowski** [LibrePlan/docker-images#6]
Hi after starting docker container I get fallowing error 
`Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory' defined in URL [jar:file:/usr/local/tomcat/webapps/libreplan/WEB-INF/lib/libreplan-business-1.4.1.jar!/libreplan-business-spring-config.xml]: Invocation of init method failed; nested exception is org.hibernate.HibernateException: Missing table: advance_assignment`

**Comment by kwoot** [comment]
Since you are the first to mention this after over 1000 deployments I wonder what is causing this.

**Comment by mariuszkopowski** [comment]
@kwoot well I have found the answer for the problem. I have fallowed this instruction:
Create manually 2 containers
Launch a PostgreSQL container
$ docker run \
   --name postgres \
   -v /absolute/path/to/folder/sql:/docker-entrypoint-initdb.d \
   -e POSTGRES_USER=libreplan \
   -e POSTGRES_PASSWORD=secret \
   -d postgres:9.4
Launch and attach the LibrePlan container
$ docker run \
  --link postgres:db \
  -p 8080:8080 \
  libreplan/libreplan:latest
Then, head your browser on http://localhost:8080/libreplan.

But then I have read again the instruction and there is an info that you have to initiate DB with SQL Script. The problem is how to do it when using only plain docker run / docker exec etc commands... 
I assume that when running docker compose it should work

**Comment by kwoot** [comment]
The docker stuff was made by a great French guy called Philippe Poumaroux. I will email him a link to this issue.

**Comment by poum** [comment]
Hi.
@kwoot is perfectly right, you need to link the libreplan container with a correctly initialized postgresql (or mysql) one.
The docker-compose file is here to make this easy.

Anyway, you could also do it manually, as explained here: https://hub.docker.com/r/libreplan/libreplan/ in "create manually 2 containers". The '-v' option in the docker command for the first (postgres) container allow postgres to launch the sql init script (see the postgres image doc in docker hub for more details).
The sql init script could be downloaded in the sql folder of this git repo. The link is also in the doc.
You have to put this sql script file in a local folder. Then you mount this folder to the postgresql container one:

`-v /absolute/path/to/folder/sql:/docker-entrypoint-initdb.d`

Sorry for the delay of my answer (but @kwoot said already almost everything)

Ok to close the issue ?
